### Listar empresas
GET http://localhost:8080/empresas

### Deletar empresa por id
DELETE http://localhost:8080/empresas/3


### Criar empresas
POST http://localhost:8080/empresas
Content-Type: application/json

{
  "nomeFantasia": "Empresa Alfa LTDA",
  "cnpj": "12.345.678/0001-90",
  "emailContato": "contato@empresa-alfa.com"
}

###

POST http://localhost:8080/empresas
Content-Type: application/json

{
  "nomeFantasia": "Beta Comércio ME",
  "cnpj": "98.765.432/0001-10",
  "emailContato": "beta@comercio.com"
}

###

POST http://localhost:8080/empresas
Content-Type: application/json

{
  "nomeFantasia": "Gamma Serviços S.A.",
  "cnpj": "11.222.333/0001-44",
  "emailContato": "servicos@gamma.com"
}

###

POST http://localhost:8080/empresas
Content-Type: application/json

{
  "nomeFantasia": "Delta Engenharia",
  "cnpj": "22.333.444/0001-55",
  "emailContato": "contato@deltaeng.com",
  "endereco": "Rua vergueiro 1211 Paraiso",
  "descricao": "aaa" 
}

###

POST http://localhost:8080/empresas
Content-Type: application/json

{
  "nomeFantasia": "Epsilon Digital",
  "cnpj": "33.444.555/0001-66",
  "emailContato": "email@epsilondigital.com"
}
