### Variáveis globais
@host = http://localhost:8080
@inscricaoId = 1
@estudanteId = 1
@vagaId = 1

POST {{host}}/inscricoes
Content-Type: application/json

{
  "dataInscricao": "2025-11-04",
  "status": "Pendente",
  "mensagemApresentacao": "Olá, estou muito interessado nesta vaga e gostaria de me candidatar.",
  "estudante": {
    "id": {{estudanteId}}
  },
  "vaga": {
    "id": {{vagaId}}
  }
}